site_name: Andersen Lab Dry Guide
theme: readthedocs
repo_url: https://github.com/Andersenlab/dry-guide


markdown_extensions:
    - admonition
    - toc:
            permalink: true
            separator: _
    - fenced_code
    - sane_lists

nav:
    - Home: index.md
    - Knowledge Base:
          - Command Line: bash.md
          - R: r.md
          - Git and Github: github.md
    - Quest:
          - Introduction: quest-intro.md
          - Nextflow: quest-nextflow.md
          - GCP: pipeline-GCPconfig.md
          - Conda: quest-conda.md
          - Docker: pipeline-docker.md
    - WI Sequencing pipelines:
          - Overview: pipeline-overview.md
          - trim-fq-nf: pipeline-trimming.md
          - alignment-nf: pipeline-alignment.md
          - wi-gatk: pipeline-wiGATK.md
          - concordance-nf: pipeline-concordance.md
          - post-gatk-nf: pipeline-postGATK.md
          - annotation-nf: pipeline-annotation-nf.md
    - Other pipelines:
          - genomes-nf: pipeline-genomes-nf.md
          - nil-ril-nf: pipeline-nil-ril.md
          - Adding NILs Sequencing Data: adding-seq-data.md
          - cegwas2-nf: pipeline-cegwas.md
          - NemaScan: pipeline-nemascan.md
    - Other things:
          - CeNDR: cendr.md
          - Backup: backup.md
          - Cloud: cloud.md
    - Andersen Labsite: labsite.md
extra_css:
    - css/version-select.css
extra_javascript:
    - js/version-select.js
