site_name: Andersen Lab Dry Guide
theme: readthedocs
repo_url: https://github.com/Andersenlab/dry-guide


markdown_extensions:
    - admonition
    - toc:
            permalink: true
            separator: _
    - fenced_code
    - sane_lists

nav:
    - Home: index.md
    - Knowledge Base:
          - Best Practices: best_practices.md
          - R: r.md
          - R Shiny: shiny.md
          - Command Line: bash.md
          - Git and Github: github.md
    - Quest:
          - Introduction: quest-intro.md
          - Data on b1059: b1059.md
          - Data on Rockfish: VAST.md
          - Nextflow: quest-nextflow.md
          - Conda: quest-conda.md
          - Docker: pipeline-docker.md
          - GCP: pipeline-GCPconfig.md
    - WI Sequencing pipelines:
          - Overview: pipeline-overview.md
          - trim-fq-nf: pipeline-trimming.md
          - alignment-nf: pipeline-alignment.md
          - wi-gatk: pipeline-wiGATK.md
          - concordance-nf: pipeline-concordance.md
          - post-gatk-nf: pipeline-postGATK.md
          - imputation: pipeline-impute.md
          - annotation-nf: pipeline-annotation-nf.md
    - Other pipelines:
          - NemaScan: pipeline-nemascan.md
          - Image Analysis: pipeline-cellprofiler.md
          - nil-ril-nf: pipeline-nil-ril.md
          - genomes-nf: pipeline-genomes-nf.md
          - cegwas2-nf: pipeline-cegwas.md
    - Other things:
          - CeNDR: cendr.md
          - Backup: backup.md
          - Cloud: cloud.md
          - Globus file sharing: sharing-globus.md
          - Andersen Labsite: labsite.md
# extra_css:
# - css/version-select.css
# extra_javascript:
# - js/version-select.js
